import { z } from 'zod'
import { lotdgCommentaryEntrySchema } from '../social/lotdg-commentary-schema'

export const lotdgSpecialEventSchema = z.object({
  stage: z.string().optional(),
  outcome: z.string().optional(),
  message_key: z.string().optional(),
  event_code: z.string().optional(),
  reward: z.string().optional(),
  hint: z.string().optional(),
  gold: z.int().optional(),
  gem: z.int().optional(),
  bet: z.int().optional(),
  try_count: z.int().optional(),
  remaining_try: z.int().optional(),
  guess_number: z.int().optional(),
  secret_number: z.int().optional(),
  minimum_number: z.int().optional(),
  maximum_number: z.int().optional(),
  maximum_try: z.int().optional(),
  win_multiplier: z.int().optional(),
  gold_gained: z.int().optional(),
  gold_lost: z.int().optional(),
  gold_lost_all: z.boolean().optional(),
  gem_gained: z.int().optional(),
  gem_lost: z.int().optional(),
  gem_spent: z.int().optional(),
  charm_gained: z.int().optional(),
  charm_lost: z.int().optional(),
  stick_broke: z.boolean().optional(),
  turn_gained: z.int().optional(),
  turn_lost: z.int().optional(),
  turn_lost_all: z.boolean().optional(),
  hit_point: z.int().optional(),
  max_hit_point_lost: z.int().optional(),
  max_hit_point_gained: z.int().optional(),
  experience_gained: z.int().optional(),
  favor_gained: z.int().optional(),
  specialty_code: z.int().optional(),
  point_gained: z.int().optional(),
  rank_gained: z.int().optional(),
  healed: z.boolean().optional(),
  already_rested: z.boolean().optional(),
  mount_name: z.string().nullable().optional(),
  mount_entered: z.boolean().optional(),
  mount_saved: z.boolean().optional(),
  mount_died: z.boolean().optional(),
  is_dwarf: z.boolean().optional(),
  is_troll_race: z.boolean().optional(),
  location_code: z.int().optional(),
  location_code_list: z.array(z.int()).optional(),
  riddle_id: z.int().optional(),
  riddle_text: z.string().optional(),
  answer_text: z.string().optional(),
  kitten_code_list: z.array(z.int()).optional(),
  section_code: z.string().optional(),
  comment_list: z.array(lotdgCommentaryEntrySchema).optional(),
  post_quota_remaining: z.int().optional(),
})

export const lotdgDarkHorseSchema = z.object({
  stage: z.string().optional(),
  outcome: z.string().optional(),
  message_key: z.string().optional(),
  started: z.boolean().optional(),
  inspected: z.boolean().optional(),
  side: z.string().optional(),
  bet: z.int().optional(),
  red: z.int().optional(),
  blue: z.int().optional(),
  player_score: z.int().optional(),
  old_man_score: z.int().optional(),
  drawn_list: z.array(z.string()).optional(),
  roll: z.int().optional(),
  roll_count: z.int().optional(),
  can_reroll: z.boolean().optional(),
  player_roll: z.int().optional(),
  old_man_roll_list: z.array(z.int()).optional(),
  gold_gained: z.int().optional(),
  gold_lost: z.int().optional(),
  cost: z.int().optional(),
  display_name: z.string().optional(),
  level: z.int().optional(),
  max_hit_point: z.int().optional(),
  gold: z.int().optional(),
  weapon_name: z.string().optional(),
  armor_name: z.string().optional(),
  attack_point: z.int().optional(),
  defence_point: z.int().optional(),
  section_code: z.string().optional(),
  comment_list: z.array(lotdgCommentaryEntrySchema).optional(),
  post_quota_remaining: z.int().optional(),
})

export const lotdgDarkHorseEnemySearchSchema = z.object({
  search_term: z.string(),
  truncated: z.boolean(),
  lookup_cost: z.int(),
  candidate_list: z.array(
    z.object({ login_name: z.string(), display_name: z.string(), level: z.int() }),
  ),
})

export type LotdgSpecialEvent = z.infer<typeof lotdgSpecialEventSchema>
export type LotdgDarkHorse = z.infer<typeof lotdgDarkHorseSchema>
export type LotdgDarkHorseEnemySearch = z.infer<typeof lotdgDarkHorseEnemySearchSchema>
