export const LOTDG_SCREEN_CODE = {
  LOGIN: 'login',
  REGISTER: 'register',
  VILLAGE: 'village',
  FOREST: 'forest',
  SPECIAL_EVENT: 'special-event',
  DARK_HORSE: 'dark-horse',
  GAME_INFORMATION: 'game-information',
  WEAPON_EDITOR: 'weapon-editor',
  ARMOR_EDITOR: 'armor-editor',
  TRAINING: 'training',
  BANK: 'bank',
  WEAPON_SHOP: 'weapon-shop',
  ARMOR_SHOP: 'armor-shop',
  INN: 'inn',
  HEALER: 'healer',
  OUTHOUSE: 'outhouse',
  STABLE: 'stable',
  GEM_TRADER: 'gem-trader',
  GRAVEYARD: 'graveyard',
  DRAGON: 'dragon',
  PLAYER_VERSUS_PLAYER: 'player-versus-player',
  BOUNTY: 'bounty',
  GYPSY: 'gypsy',
  HALL_OF_FAME: 'hall-of-fame',
  WARRIOR_LIST: 'warrior-list',
  BIOGRAPHY: 'biography',
  GARDENS: 'gardens',
  VETERANS: 'veterans',
  MOTD: 'motd',
  PREFERENCE: 'preference',
  NEWS: 'news',
  MAIL: 'mail',
  PETITION: 'petition',
  ADMINISTRATION: 'administration',
} as const

export type LotdgScreenCode = (typeof LOTDG_SCREEN_CODE)[keyof typeof LOTDG_SCREEN_CODE]

export const LOTDG_SCREEN_TITLE_LABEL_PATH: Record<LotdgScreenCode, string> = {
  login: 'screen.login',
  register: 'screen.register',
  village: 'screen.village',
  forest: 'screen.forest',
  'special-event': 'screen.special-event',
  'dark-horse': 'screen.dark-horse',
  'game-information': 'screen.game-information',
  'weapon-editor': 'screen.weapon-editor',
  'armor-editor': 'screen.armor-editor',
  training: 'screen.training',
  bank: 'screen.bank',
  'weapon-shop': 'screen.weapon-shop',
  'armor-shop': 'screen.armor-shop',
  inn: 'screen.inn',
  healer: 'screen.healer',
  outhouse: 'screen.outhouse',
  stable: 'screen.stable',
  'gem-trader': 'screen.gem-trader',
  graveyard: 'screen.graveyard',
  dragon: 'screen.dragon',
  'player-versus-player': 'screen.player-versus-player',
  bounty: 'screen.bounty',
  gypsy: 'screen.gypsy',
  'hall-of-fame': 'screen.hall-of-fame',
  'warrior-list': 'screen.warrior-list',
  biography: 'screen.biography',
  gardens: 'screen.gardens',
  veterans: 'screen.veterans',
  motd: 'screen.motd',
  preference: 'screen.preference',
  news: 'screen.news',
  mail: 'screen.mail',
  petition: 'screen.petition',
  administration: 'screen.administration',
}
