import { LOTDG_SCREEN_CODE, type LotdgScreenCode } from '../router/lotdg-screen-code'

/**
 * 본문 배경 장면. 레거시 대응 — reference/templates/yarbrough.css 의
 * td.village / td.forest / td.dragon 이 화면별로 배경 그림을 깔던 것을,
 * 실제로 존재하는 에셋(village / forest / castle)에 맞춰 정리한다.
 */
export const LOTDG_STAGE_SCENE_CODE = {
  NONE: 'none',
  VILLAGE: 'village',
  FOREST: 'forest',
  CASTLE: 'castle',
} as const

export type LotdgStageSceneCode =
  (typeof LOTDG_STAGE_SCENE_CODE)[keyof typeof LOTDG_STAGE_SCENE_CODE]

const SCENE_BY_SCREEN_CODE: Partial<Record<LotdgScreenCode, LotdgStageSceneCode>> = {
  [LOTDG_SCREEN_CODE.VILLAGE]: LOTDG_STAGE_SCENE_CODE.VILLAGE,
  [LOTDG_SCREEN_CODE.INN]: LOTDG_STAGE_SCENE_CODE.VILLAGE,
  [LOTDG_SCREEN_CODE.HEALER]: LOTDG_STAGE_SCENE_CODE.VILLAGE,
  [LOTDG_SCREEN_CODE.OUTHOUSE]: LOTDG_STAGE_SCENE_CODE.VILLAGE,
  [LOTDG_SCREEN_CODE.STABLE]: LOTDG_STAGE_SCENE_CODE.VILLAGE,
  [LOTDG_SCREEN_CODE.WEAPON_SHOP]: LOTDG_STAGE_SCENE_CODE.VILLAGE,
  [LOTDG_SCREEN_CODE.ARMOR_SHOP]: LOTDG_STAGE_SCENE_CODE.VILLAGE,
  [LOTDG_SCREEN_CODE.GEM_TRADER]: LOTDG_STAGE_SCENE_CODE.VILLAGE,
  [LOTDG_SCREEN_CODE.BANK]: LOTDG_STAGE_SCENE_CODE.VILLAGE,
  [LOTDG_SCREEN_CODE.GARDENS]: LOTDG_STAGE_SCENE_CODE.VILLAGE,
  [LOTDG_SCREEN_CODE.VETERANS]: LOTDG_STAGE_SCENE_CODE.VILLAGE,
  [LOTDG_SCREEN_CODE.GYPSY]: LOTDG_STAGE_SCENE_CODE.VILLAGE,
  [LOTDG_SCREEN_CODE.FOREST]: LOTDG_STAGE_SCENE_CODE.FOREST,
  [LOTDG_SCREEN_CODE.SPECIAL_EVENT]: LOTDG_STAGE_SCENE_CODE.FOREST,
  [LOTDG_SCREEN_CODE.DARK_HORSE]: LOTDG_STAGE_SCENE_CODE.FOREST,
  [LOTDG_SCREEN_CODE.GRAVEYARD]: LOTDG_STAGE_SCENE_CODE.FOREST,
  [LOTDG_SCREEN_CODE.TRAINING]: LOTDG_STAGE_SCENE_CODE.CASTLE,
  [LOTDG_SCREEN_CODE.DRAGON]: LOTDG_STAGE_SCENE_CODE.CASTLE,
  [LOTDG_SCREEN_CODE.PLAYER_VERSUS_PLAYER]: LOTDG_STAGE_SCENE_CODE.CASTLE,
}

export function resolveStageSceneCode(screenCode: LotdgScreenCode): LotdgStageSceneCode {
  return SCENE_BY_SCREEN_CODE[screenCode] ?? LOTDG_STAGE_SCENE_CODE.NONE
}
